### ISSUE TITLE
Constants in linear model fit

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaAI/MLJGLMInterface.jl#11]
I'm trying to fix the dropping of feature names by this interface, as also listed in one of the TODOs:

https://github.com/JuliaAI/MLJGLMInterface.jl/blob/7468b6d524221b9efc446d5c1ce28c2c872a2357/src/MLJGLMInterface.jl#L5

To do so, I'm looking into using `fit(..., @formula, data)` instead of `fit(..., X, y)`. However, `@formula(y ~ a + b)` will always add a constant, whereas `X`, `y` will not.

Is there a reason why `MLJGLMInterface` by default is not using a constant?

**Comment by rikhuijzer** [comment]
> Just to clarify, are you suggesting there may be a bug in the existing implementation, or asking for assistance on getting the new feature working?

I was mainly confused about why `MLJGLMInterface.jl` defaults to no constant and `GLM.jl` defaults to a constant. I guess it's not really a problem. People can always use `fit_intercept=true`.

**Comment by ablaom** [comment]
Now I'm confused. It seem to me that `fit_intercept=true` *is* the default:

```julia
using MLJ
julia> M = @iload LinearRegressor pkg = GLM
julia> m=M()
LinearRegressor(
    fit_intercept = true,
    allowrankdeficient = false,
    offsetcol = nothing)
```

What am I missing? Is it one of the other models with the weird default?
