### ISSUE TITLE
Allow fitting arbitrary `@formula`s

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaAI/MLJGLMInterface.jl#13]
Currently, there are only a few models available via this interface. I suggest implementing also adding a `FormulaRegressor` for arbitrary formulas, via `StatsModels.@formula(...)`.

@ablaom, what do you think? Would this make sense to add this to this interface?

**Comment by ablaom** [comment]
Okay I've created a new issue [here](https://github.com/JuliaAI/MLJModels.jl/issues/406) specific to the suggestion not immediately addresses in the initial comment. So further comment on that should go there, thanks.
