### ISSUE TITLE
GLM compat broken

### ISSUE THREAD

**Issue by olivierlabayle** [JuliaAI/MLJGLMInterface.jl#34]
Hi,

I think there has been a compatibility issue introduced by GLM 1.8. To reproduce, just instantiate the package and run the tests.

I am struggling with identifying the exact issue because successive call to add GLM@v1.x seem to result in non reproducible manifest files (which is more a Julia issue)... That being said I think it is related to the intercept which has become the first element in the coefficients and not the last as expected by the interface.

I don't have much time to fix the issue but as a hot fix, changing the compat to GLM = "1.4 - 1.7" solves the issue on my end. I have for some reason lost permissions on this package but happy to push the fix if granted permissions again.

**Comment by rikhuijzer** [comment]
Well spotted! Thanks for reporting.

The issue seems to be introduced by the switch from GLM 1.8.1 to 1.8.2. This switch moved StatsModels over from 0.6.33 to 0.7.1. 

The precise issue is the following. With GLM 1.8.1:
```julia
julia> MLJGLMInterface.glm_formula(model, [:a, :b]) |> string
"y ~ a + b + 1"
```
with GLM 1.8.2:
```julia
julia> MLJGLMInterface.glm_formula(model, [:a, :b]) |> string
"y ~ 1 + a + b"
```
Root cause at https://github.com/JuliaStats/StatsModels.jl/issues/289. I'm working on a fix

**Comment by kleinschmidt** [comment]
Just for my own edification, why does MLJ require that the intercept term go at the end?  The convention in GLM.jl (and R formulae etc.) is that terms get sorted in order of increasing "degree" (where intercept has degree 0, main effects like `:a`, `:b`, etc. have degree 1, interactions like `:a & :b` have degree 2, `a & b & c` have degree 3, etc.).

**Comment by rikhuijzer** [comment]
Because it assumed the intercept to be at the end when making predictions. For this package, it actually doesn’t matter too much since we can easily flip it as done in #35
