### ISSUE TITLE
Should we also make the _p_-values available?

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaAI/MLJGLMInterface.jl#36]
By default, GLM gives a table including _p_-values. For example (from the docs):

```
julia> using DataFrames, GLM

julia> data = DataFrame(X=[1,2,3], Y=[2,4,7])
3×2 DataFrame
 Row │ X      Y
     │ Int64  Int64
─────┼──────────────
   1 │     1      2
   2 │     2      4
   3 │     3      7

julia> ols = lm(@formula(Y ~ X), data)
StatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, LinearAlgebra.CholeskyPivoted{Float64, Matrix{Float64}}}}, Matrix{Float64}}

Y ~ 1 + X

Coefficients:
─────────────────────────────────────────────────────────────────────────
                 Coef.  Std. Error      t  Pr(>|t|)  Lower 95%  Upper 95%
─────────────────────────────────────────────────────────────────────────
(Intercept)  -0.666667    0.62361   -1.07    0.4788   -8.59038    7.25704
X             2.5         0.288675   8.66    0.0732   -1.16797    6.16797
─────────────────────────────────────────────────────────────────────────
```
But this report is not passed on through the MLJ interface. Should we add it?

This could be useful for people in order to "integrate explanation and prediction" [1]. Or, in other words, to make it easier for people to report both predictive performance scores **and** frequentist metrics. Having only predictive cross-validated scores is not necessarily helpful in understanding the model and having only _p_-values is prone to overfitting. Hence, reporting both would make research more reliable.

@ablaom If you agree that this is a good idea, then I can make a PR. I'll probably add a field to `MLJGLMInterface.FitResult` and then try to document clearly that the report is available there.

[1]: Hofman, J.M., Watts, D.J., Athey, S. et al. Integrating explanation and prediction in computational social science. Nature 595, 181–188 (2021). https://doi.org/10.1038/s41586-021-03659-0

**Comment by rikhuijzer** [comment]
Thanks. Sounds reasonable

**Comment by OkonSamuel** [comment]
> Thanks. Sounds reasonable

I guess we should add an example on how to do this in the docstrings. To make this more discoverable.
